apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: x529u8j2l-nodejs 
  janus-idp.io/tekton: x529u8j2l-nodejs
  backstage.io/kubernetes-id: x529u8j2l-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: x529u8j2l-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  